# Tasca M3 T01

## Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [4]:
import numpy as np

Array= np.random.randint(0, 101, size=(100))
print(Array)

[ 58  34   2  34  77  15  24  72  25  48  77  45  90  60  78  81  86  16
  71  89  39  95  73  38  39  74  71  91  56  28  18  19  96   6  67  39
  83  98   2  52  65  28   2  19  50  23  62  54  18  97  85  90  85   1
   0  66  68  64  11  53  48  57  33  86  31  28  47  49  32  94  25  42
  51  87  30  54  28  83  37  22  64  37  77  32  88  29  80  30  58 100
  53  80  86  50  88  96  63  56  32  71]


In [5]:
def resum_stdtc(arr):
    if arr.ndim != 1:
        print("Error: l'array té més d'una dimensió")
    else:
        print("Resum estadístic:")
        print("Mínim: ", np.min(arr))
        print("Màxim: ", np.max(arr))
        print("Mitjana: ", np.mean(arr))
        print("Mediana: ", np.median(arr))
        print("Desviació estàndard: ", np.std(arr))
        print("Quartil 1: ", np.percentile(arr, 25))
        print("Quartil 3: ", np.percentile(arr, 75))

In [6]:
resum_stdtc(Array)

Resum estadístic:
Mínim:  0
Màxim:  100
Mitjana:  53.41
Mediana:  53.5
Desviació estàndard:  27.45690987711472
Quartil 1:  30.75
Quartil 3:  77.25


## Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [7]:
matriu = np.random.randint(0, 101, size=(5, 5))
print(matriu)

[[ 84  40  87  39  50]
 [ 22  32  20  91  98]
 [  8  57  46  89  41]
 [ 29  71  10 100   1]
 [ 21  49  90 100  78]]


## Exercici 3

Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [8]:
# Versió que fa un marc a la matriu

def filesicolumnes(matriz):
    print("Matriu original:")
    print(matriz)
    
    matriu_mod_C = np.concatenate([matriz, np.sum(matriz, axis=1, keepdims=True)], axis=1)

    print("Matriu amb sumes por fila:")
    print(matriu_mod_C)

    fila_sumes = np.zeros((1, matriu_mod_C.shape[1]), dtype=np.int64)
    fila_sumes[0, :-1] = np.sum(matriz, axis=0)
    fila_sumes[0, -1] = np.sum(matriz)
    matriu_mod_F = np.concatenate([matriu_mod_C, fila_sumes], axis=0)

    print("Matriu final amb sumes per fila y columna:")
    print(matriu_mod_F)

In [9]:
# Versió que no més fa la suma

def sumar(matriz):
    trnspsc = np.transpose(matriz)
    sum_filas = np.sum(matriz, axis=1)
    sum_columnas = np.sum(trnspsc, axis=0)
    matriz_suma = np.hstack
    print("Suma de filas:")
    for fila in sum_filas.reshape(-1, 1):
        print(fila[0])
    print("Suma de columnas:\n", sum_columnas)

In [10]:
sumar(matriu)

Suma de filas:
300
263
241
211
338
Suma de columnas:
 [300 263 241 211 338]


In [11]:
filesicolumnes(matriu)

Matriu original:
[[ 84  40  87  39  50]
 [ 22  32  20  91  98]
 [  8  57  46  89  41]
 [ 29  71  10 100   1]
 [ 21  49  90 100  78]]
Matriu amb sumes por fila:
[[ 84  40  87  39  50 300]
 [ 22  32  20  91  98 263]
 [  8  57  46  89  41 241]
 [ 29  71  10 100   1 211]
 [ 21  49  90 100  78 338]]
Matriu final amb sumes per fila y columna:
[[  84   40   87   39   50  300]
 [  22   32   20   91   98  263]
 [   8   57   46   89   41  241]
 [  29   71   10  100    1  211]
 [  21   49   90  100   78  338]
 [ 164  249  253  419  268 1353]]


## Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [12]:
import numpy as np
import scipy.stats

In [16]:
A = np.random.randint(1, 100, size=10)
B = np.random.randint(1, 100, size=10)
print(A,B)

[65 84 74 55 52 52 28 81 25 13] [88 35 70 58 38 50 36 39 22 96]


Sabem que les dades són numériques, a més sent que es un random randint podem assumir també la seva normalitat llavor l'adeqüat seria fer Pearsons

$$r_{xy} = \frac{\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{\sqrt{\sum_{i=1}^{n}(x_i - \bar{x})^2} \sqrt{\sum_{i=1}^{n}(y_i - \bar{y})^2}}$$

- **xi** i **yi** són els valors de la i-aquesta en els conjunts de dades 
- $\bar{x}$ i $\bar{y}$ són les mitjanes
- **n** és la quantitat d' observacions en els conjunts de dades.

    _Recordem que X correspondrà a la variable independent i la Y a la dependent, a més si es donen dos valors s'assumirà que el primer correspondrà a X i el segon a Y_

In [17]:
import numpy as np

def pearson(x, y):
    mean_x = np.mean(x)
    mean_y = np.mean(y)
    std_x = np.std(x)
    std_y = np.std(y)
    cov_xy = np.cov(x, y)[0, 1]
    corr = cov_xy / (std_x * std_y)
    print("El coeficient de correlació és:", corr)
    if corr == 1:
        print("Existeix una correlació positiva perfecta entre les dues variables")
    elif corr > 0:
        print("Existeix una correlació positiva entre les dues variables")
    elif corr == 0:
        print("No hi ha correlació entre les dues variables")
    elif -1 < corr < 0:
        print("Existeix una correlació negativa entre les dues variables")
    elif corr == -1:
        print("Existeix una correlació negativa perfecta entre les dues variables")
    elif corr < -1 or corr > 1:
        print("El coeficient de correlació està fora de rang (-1 a 1).")
    return corr

In [18]:
pearson(A, B)

El coeficient de correlació és: -0.11835129576573845
Existeix una correlació negativa entre les dues variables


-0.11835129576573845

Una correlació negativa és refereix que quan una augmenta l'altre disminueix el que em sorpren una mica perquè son una variables generades de forma aleatòria